"use client";
import type { Metadata } from "next";

import "./globals.scss";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import { ReduxProvider } from "@/redux/provider";

const { NEXT_PUBLIC_PAGE_TITLE } = process.env;

 const metadata: Metadata = {
  title: NEXT_PUBLIC_PAGE_TITLE,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body >

        <ReduxProvider>{children} </ReduxProvider>
      </body>
    </html>
  );
}
